#!/bin/sh

#userresources=$HOME/.Xresources
#usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#############################################

# $HOME/.config/autostart &
$HOME/.local/bin/scripts/set-tv-creen

# Set keyboard with alt-gr dead keys for accents and extra symbols
setxkbmap -model pc105+inet \
          -layout us \
          -variant altgr-intl \
          -option terminate:ctrl_alt_bksp

# Configure Monitors
# $HOME/.config/screens.sh
# $HOME/.local/bin/scripts/screen-layout-vertical-right
# $HOME/.local/bin/scripts/set-tv-creen

# Xresources
xrdb -merge $HOME/.config/x/Xresources
# Fix x-shaped cursor
xsetroot -cursor_name left_ptr

# remap buttons on Trackball for left hand use 
#      (BotR: primary click, TopL: secondary click, BotL: middle click)
xinput set-button-map "Kensington Expert Mouse" 2 3 1 4 5 6 7 8 9

# decrease trackball speed (not acceleration!)
xinput set-prop "Kensington Expert Mouse" \
                "Coordinate Transformation Matrix" \
                1, 0, 0,    0, 1, 0,    0, 0, 2
# Start stuff
nm-applet &
wired &
pgrep -x sxhkd > /dev/null || sxhkd &
emacs --daemon &
thunar --daemon &
#discord --start-minimized &
#qpwgraph --minimized --activated ~/.config/qpwgraph/mpv2webrtc_voice_and_mic2speakers.qpwgraph &
#lxsession &
#qbittorrent --no-splash &

exec bspwm
