#! /bin/sh

# Foreplay
feh --bg-fill --no-fehbg ~/.config/wallpaper
killall polybar ; polybar --reload mybar &
killall picom ; picom &

# BSPWM config: 

bspc monitor eDP1 -d {1..10} # ⼀ 二 三 四 五 六 #七 八 九 十
bspc config border_width 1
bspc config window_gap 6
bspc config focused_border_color '#ffffff'
bspc config presel_feedback_color '#ffffff'

## Window management
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          false
#bspc config ignore_ewmh_fullscreen  all

## Mouse 
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor false
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_corner 
bspc config pointer_action3         resize_side

## Misc
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Nsxiv state=floating rectangle=800x600+0+0 center=true
bspc rlue -a xterm state=floating rectangle=800x600+0+0 center=true
