# disable on-screen-controls as the thumbnail script requires
osc=no

# enable fuzzy searching
sub-auto=fuzzy

# see: https://wiki.archlinux.org/title/Mpv#High_quality_configurations
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample

