# lazy.toml - by OldarkDesu

# Default colors
[colors.primary]
background = '#111111'
foreground = '#cccccc'

# Normal colors
[colors.normal]
black   = '#222222'
red     = '#aa0033'
green   = '#00BB66'
yellow  = '#FF8800'
blue    = '#9900ff'
magenta = '#cc0088'
cyan    = '#00bbFF'
white   = '#cccccc'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#FF0044'
green   = '#00FF88'
yellow  = '#FFAA00'
blue    = '#aa44ff'
magenta = '#ff0099'
cyan    = '#00ffFF'
white   = '#ffffff'
